name: 'Create-AQAvit-Release'

on:
  workflow_dispatch:
    inputs:
      aqavitTagValue:
        description: The value of the tag to use (such as v1.0.0)
        required: true
        type: string
      reposToTag:
        description: Comma-separated set of repos to tag (such as adoptium/aqa-tests,adoptium/TKG,adoptium/STF)
        required: false
        default: 'adoptium/aqa-tests,adoptium/TKG,adoptium/STF,adoptium/aqa-systemtest,adoptium/openj9-systemtest,adoptium/bumblebench'
        type: string
      jdkReleaseTags:
        description: Comma-separated set of JDK release prefix tags expected (such as 22.0.0,21.0.3,17.0.11,11.0.23,8u411)
        required: false
        type: string
      isDryRun:
        description: 0 or 1, whether to push tags and changes to repos, or not
        required: false
        type: boolean

jobs:
  createAQAvitRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run tagRepos.sh
        run: ./tagRepos.sh ${{ inputs.aqavitTagValue }}

#      - name: Run createRelBranch.sh
#        run: ./createRelBranch.sh ${{ inputs.aqavitTagValue }} ${{ inputs.jdkReleaseTags }}
        
